"""initial schema

Revision ID: 4d2b3e1703af
Revises: 
Create Date: 2026-06-17 18:10:41.966077
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4d2b3e1703af'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions for accent-insensitive trigram search on candidate/person names.
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coalition',
    sa.Column('sq_coligacao', sa.String(length=32), nullable=False),
    sa.Column('nm_coligacao', sa.String(length=255), nullable=True),
    sa.Column('ds_composicao_coligacao', sa.Text(), nullable=True),
    sa.Column('ano_eleicao', sa.Integer(), nullable=True),
    sa.Column('sg_uf', sa.String(length=2), nullable=True),
    sa.Column('cd_cargo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sq_coligacao')
    )
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('titulo_eleitoral', sa.String(length=20), nullable=True),
    sa.Column('nome_civil', sa.String(length=255), nullable=True),
    sa.Column('nome_normalizado', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('uf_nascimento', sa.String(length=2), nullable=True),
    sa.Column('match_confidence_tier', sa.Enum('auto_strong', 'auto_weak', 'review', name='confidencetier'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_cpf'), 'person', ['cpf'], unique=True)
    op.create_index(op.f('ix_person_nome_normalizado'), 'person', ['nome_normalizado'], unique=False)
    op.create_index(op.f('ix_person_titulo_eleitoral'), 'person', ['titulo_eleitoral'], unique=False)
    op.create_table('raw_ingestion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collector_name', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_generated_at', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_ingestion_collector_name'), 'raw_ingestion', ['collector_name'], unique=False)
    op.create_index(op.f('ix_raw_ingestion_content_hash'), 'raw_ingestion', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_ingestion_source_url'), 'raw_ingestion', ['source_url'], unique=False)
    op.create_table('candidacy',
    sa.Column('sq_candidato', sa.String(length=32), nullable=False),
    sa.Column('ano_eleicao', sa.Integer(), nullable=False),
    sa.Column('nr_turno', sa.Integer(), nullable=False),
    sa.Column('cd_eleicao', sa.Integer(), nullable=True),
    sa.Column('ds_eleicao', sa.String(length=255), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('cpf_raw', sa.String(length=14), nullable=True),
    sa.Column('titulo_raw', sa.String(length=20), nullable=True),
    sa.Column('nome_candidato', sa.String(length=255), nullable=True),
    sa.Column('nome_urna', sa.String(length=255), nullable=True),
    sa.Column('nome_normalizado', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cd_cargo', sa.Integer(), nullable=True),
    sa.Column('ds_cargo', sa.String(length=64), nullable=True),
    sa.Column('sg_uf', sa.String(length=2), nullable=True),
    sa.Column('sg_ue', sa.String(length=8), nullable=True),
    sa.Column('nm_ue', sa.String(length=120), nullable=True),
    sa.Column('nr_candidato', sa.String(length=8), nullable=True),
    sa.Column('sg_partido', sa.String(length=32), nullable=True),
    sa.Column('nr_partido', sa.Integer(), nullable=True),
    sa.Column('nm_partido', sa.String(length=120), nullable=True),
    sa.Column('sq_coligacao', sa.String(length=32), nullable=True),
    sa.Column('ds_situacao_candidatura', sa.String(length=64), nullable=True),
    sa.Column('ds_detalhe_situacao_cand', sa.String(length=120), nullable=True),
    sa.Column('ds_sit_tot_turno', sa.String(length=64), nullable=True),
    sa.Column('st_reeleicao', sa.String(length=8), nullable=True),
    sa.Column('is_majoritario', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['sq_coligacao'], ['coalition.sq_coligacao'], ),
    sa.PrimaryKeyConstraint('sq_candidato')
    )
    op.create_index(op.f('ix_candidacy_ano_eleicao'), 'candidacy', ['ano_eleicao'], unique=False)
    op.create_index(op.f('ix_candidacy_cpf_raw'), 'candidacy', ['cpf_raw'], unique=False)
    op.create_index(op.f('ix_candidacy_ds_cargo'), 'candidacy', ['ds_cargo'], unique=False)
    op.create_index(op.f('ix_candidacy_nome_normalizado'), 'candidacy', ['nome_normalizado'], unique=False)
    op.create_index(op.f('ix_candidacy_person_id'), 'candidacy', ['person_id'], unique=False)
    op.create_index(op.f('ix_candidacy_sg_uf'), 'candidacy', ['sg_uf'], unique=False)
    op.create_index(op.f('ix_candidacy_titulo_raw'), 'candidacy', ['titulo_raw'], unique=False)
    op.create_table('mandate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('house', sa.Enum('CAMARA', 'SENADO', name='house'), nullable=False),
    sa.Column('house_member_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('id_legislatura', sa.Integer(), nullable=False),
    sa.Column('nome_parlamentar', sa.String(length=255), nullable=True),
    sa.Column('sigla_partido', sa.String(length=32), nullable=True),
    sa.Column('sigla_uf', sa.String(length=2), nullable=True),
    sa.Column('condicao_eleitoral', sa.String(length=32), nullable=True),
    sa.Column('situacao', sa.String(length=64), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house', 'house_member_id', 'id_legislatura')
    )
    op.create_index(op.f('ix_mandate_house'), 'mandate', ['house'], unique=False)
    op.create_index(op.f('ix_mandate_house_member_id'), 'mandate', ['house_member_id'], unique=False)
    op.create_index(op.f('ix_mandate_id_legislatura'), 'mandate', ['id_legislatura'], unique=False)
    op.create_index(op.f('ix_mandate_person_id'), 'mandate', ['person_id'], unique=False)
    op.create_index(op.f('ix_mandate_sigla_uf'), 'mandate', ['sigla_uf'], unique=False)
    op.create_table('person_identifier_alias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'alias_type', 'value')
    )
    op.create_index(op.f('ix_person_identifier_alias_person_id'), 'person_identifier_alias', ['person_id'], unique=False)
    op.create_table('attendance_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('house_member_id', sa.String(length=32), nullable=False),
    sa.Column('id_evento', sa.String(length=32), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('derivation', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_evento', 'house_member_id')
    )
    op.create_index(op.f('ix_attendance_record_house_member_id'), 'attendance_record', ['house_member_id'], unique=False)
    op.create_index(op.f('ix_attendance_record_mandate_id'), 'attendance_record', ['mandate_id'], unique=False)
    op.create_table('candidate_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sq_candidato', sa.String(length=32), nullable=False),
    sa.Column('nr_ordem_bem', sa.Integer(), nullable=False),
    sa.Column('ds_tipo_bem', sa.String(length=255), nullable=True),
    sa.Column('ds_bem', sa.Text(), nullable=True),
    sa.Column('vr_bem', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dt_ultima_atualizacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sq_candidato', 'nr_ordem_bem')
    )
    op.create_index(op.f('ix_candidate_asset_sq_candidato'), 'candidate_asset', ['sq_candidato'], unique=False)
    op.create_table('candidate_mandate_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sq_candidato', sa.String(length=32), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('match_method', sa.Enum('cpf_exact', 'titulo_exact', 'probabilistic', 'manual', name='matchmethod'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_tier', sa.Enum('auto_strong', 'auto_weak', 'review', name='confidencetier'), nullable=False),
    sa.Column('is_incumbent_reelection', sa.Boolean(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=True),
    sa.Column('resolver', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sq_candidato', 'mandate_id')
    )
    op.create_index(op.f('ix_candidate_mandate_link_confidence_tier'), 'candidate_mandate_link', ['confidence_tier'], unique=False)
    op.create_index(op.f('ix_candidate_mandate_link_is_incumbent_reelection'), 'candidate_mandate_link', ['is_incumbent_reelection'], unique=False)
    op.create_index(op.f('ix_candidate_mandate_link_mandate_id'), 'candidate_mandate_link', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_candidate_mandate_link_person_id'), 'candidate_mandate_link', ['person_id'], unique=False)
    op.create_index(op.f('ix_candidate_mandate_link_sq_candidato'), 'candidate_mandate_link', ['sq_candidato'], unique=False)
    op.create_table('expense',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('house', sa.Enum('CAMARA', 'SENADO', name='house'), nullable=False),
    sa.Column('house_member_id', sa.String(length=32), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('tipo_despesa', sa.String(length=255), nullable=True),
    sa.Column('valor_documento', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_glosa', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cnpj_cpf_fornecedor', sa.String(length=20), nullable=True),
    sa.Column('nome_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('cod_documento', sa.String(length=32), nullable=False),
    sa.Column('num_documento', sa.String(length=64), nullable=False),
    sa.Column('url_documento', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_member_id', 'ano', 'mes', 'cod_documento', 'num_documento')
    )
    op.create_index(op.f('ix_expense_ano'), 'expense', ['ano'], unique=False)
    op.create_index(op.f('ix_expense_house_member_id'), 'expense', ['house_member_id'], unique=False)
    op.create_index(op.f('ix_expense_mandate_id'), 'expense', ['mandate_id'], unique=False)
    op.create_table('government_proposal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sq_candidato', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sq_candidato', 'content_hash')
    )
    op.create_index(op.f('ix_government_proposal_sq_candidato'), 'government_proposal', ['sq_candidato'], unique=False)
    op.create_table('proposition',
    sa.Column('proposition_id', sa.String(length=32), nullable=False),
    sa.Column('house', sa.Enum('CAMARA', 'SENADO', name='house'), nullable=False),
    sa.Column('authoring_mandate_id', sa.Uuid(), nullable=True),
    sa.Column('sigla_tipo', sa.String(length=16), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('data_apresentacao', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['authoring_mandate_id'], ['mandate.id'], ),
    sa.PrimaryKeyConstraint('proposition_id')
    )
    op.create_index(op.f('ix_proposition_authoring_mandate_id'), 'proposition', ['authoring_mandate_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sq_candidato', sa.String(length=32), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('candidate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mandate_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'match', 'no_match', 'uncertain', name='reviewstatus'), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sq_candidato', 'mandate_id')
    )
    op.create_index(op.f('ix_review_queue_mandate_id'), 'review_queue', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_review_queue_sq_candidato'), 'review_queue', ['sq_candidato'], unique=False)
    op.create_index(op.f('ix_review_queue_status'), 'review_queue', ['status'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('house_member_id', sa.String(length=32), nullable=False),
    sa.Column('id_votacao', sa.String(length=64), nullable=False),
    sa.Column('id_proposicao', sa.String(length=32), nullable=True),
    sa.Column('tipo_voto', sa.String(length=32), nullable=True),
    sa.Column('data_votacao', sa.Date(), nullable=True),
    sa.Column('orientacao_partido', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_votacao', 'house_member_id')
    )
    op.create_index(op.f('ix_vote_house_member_id'), 'vote', ['house_member_id'], unique=False)
    op.create_index(op.f('ix_vote_id_votacao'), 'vote', ['id_votacao'], unique=False)
    op.create_index(op.f('ix_vote_mandate_id'), 'vote', ['mandate_id'], unique=False)
    # ### end Alembic commands ###

    # Trigram GIN indexes for fast fuzzy/ILIKE candidate search (front + blocking).
    op.create_index(
        "ix_candidacy_nome_norm_trgm", "candidacy", ["nome_normalizado"],
        postgresql_using="gin", postgresql_ops={"nome_normalizado": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_person_nome_norm_trgm", "person", ["nome_normalizado"],
        postgresql_using="gin", postgresql_ops={"nome_normalizado": "gin_trgm_ops"},
    )


def downgrade() -> None:
    op.drop_index("ix_person_nome_norm_trgm", table_name="person")
    op.drop_index("ix_candidacy_nome_norm_trgm", table_name="candidacy")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_mandate_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_id_votacao'), table_name='vote')
    op.drop_index(op.f('ix_vote_house_member_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_review_queue_status'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_sq_candidato'), table_name='review_queue')
    op.drop_index(op.f('ix_review_queue_mandate_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_proposition_authoring_mandate_id'), table_name='proposition')
    op.drop_table('proposition')
    op.drop_index(op.f('ix_government_proposal_sq_candidato'), table_name='government_proposal')
    op.drop_table('government_proposal')
    op.drop_index(op.f('ix_expense_mandate_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_house_member_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_ano'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_candidate_mandate_link_sq_candidato'), table_name='candidate_mandate_link')
    op.drop_index(op.f('ix_candidate_mandate_link_person_id'), table_name='candidate_mandate_link')
    op.drop_index(op.f('ix_candidate_mandate_link_mandate_id'), table_name='candidate_mandate_link')
    op.drop_index(op.f('ix_candidate_mandate_link_is_incumbent_reelection'), table_name='candidate_mandate_link')
    op.drop_index(op.f('ix_candidate_mandate_link_confidence_tier'), table_name='candidate_mandate_link')
    op.drop_table('candidate_mandate_link')
    op.drop_index(op.f('ix_candidate_asset_sq_candidato'), table_name='candidate_asset')
    op.drop_table('candidate_asset')
    op.drop_index(op.f('ix_attendance_record_mandate_id'), table_name='attendance_record')
    op.drop_index(op.f('ix_attendance_record_house_member_id'), table_name='attendance_record')
    op.drop_table('attendance_record')
    op.drop_index(op.f('ix_person_identifier_alias_person_id'), table_name='person_identifier_alias')
    op.drop_table('person_identifier_alias')
    op.drop_index(op.f('ix_mandate_sigla_uf'), table_name='mandate')
    op.drop_index(op.f('ix_mandate_person_id'), table_name='mandate')
    op.drop_index(op.f('ix_mandate_id_legislatura'), table_name='mandate')
    op.drop_index(op.f('ix_mandate_house_member_id'), table_name='mandate')
    op.drop_index(op.f('ix_mandate_house'), table_name='mandate')
    op.drop_table('mandate')
    op.drop_index(op.f('ix_candidacy_titulo_raw'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_sg_uf'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_person_id'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_nome_normalizado'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_ds_cargo'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_cpf_raw'), table_name='candidacy')
    op.drop_index(op.f('ix_candidacy_ano_eleicao'), table_name='candidacy')
    op.drop_table('candidacy')
    op.drop_index(op.f('ix_raw_ingestion_source_url'), table_name='raw_ingestion')
    op.drop_index(op.f('ix_raw_ingestion_content_hash'), table_name='raw_ingestion')
    op.drop_index(op.f('ix_raw_ingestion_collector_name'), table_name='raw_ingestion')
    op.drop_table('raw_ingestion')
    op.drop_index(op.f('ix_person_titulo_eleitoral'), table_name='person')
    op.drop_index(op.f('ix_person_nome_normalizado'), table_name='person')
    op.drop_index(op.f('ix_person_cpf'), table_name='person')
    op.drop_table('person')
    op.drop_table('coalition')
    # ### end Alembic commands ###
