"""campaign finance + emendas tables

Revision ID: d7343ea3ec96
Revises: a1c4f7e21b05
Create Date: 2026-08-18 10:29:17.236393
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd7343ea3ec96'
down_revision: str | None = 'a1c4f7e21b05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Enums shared by several of the tables below are created once, explicitly, so
    # the per-table DDL can reference them with create_type=False. `matchmethod` and
    # `confidencetier` already exist from the initial schema.
    postgresql.ENUM(
        'final', 'parcial', 'relatorio_financeiro', 'regularizacao_omissao', 'outro',
        name='accountfiling',
    ).create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amendment_author_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('siop_author_code', sa.String(length=16), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('author_name_raw', sa.String(length=255), nullable=True),
    sa.Column('match_method', postgresql.ENUM('cpf_exact', 'titulo_exact', 'probabilistic', 'manual', name='matchmethod', create_type=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_tier', postgresql.ENUM('auto_strong', 'auto_weak', 'review', name='confidencetier', create_type=False), nullable=False),
    sa.Column('resolver', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siop_author_code', 'ano')
    )
    op.create_index(op.f('ix_amendment_author_link_ano'), 'amendment_author_link', ['ano'], unique=False)
    op.create_index(op.f('ix_amendment_author_link_mandate_id'), 'amendment_author_link', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_amendment_author_link_person_id'), 'amendment_author_link', ['person_id'], unique=False)
    op.create_index(op.f('ix_amendment_author_link_siop_author_code'), 'amendment_author_link', ['siop_author_code'], unique=False)
    op.create_table('budget_amendment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('codigo_emenda', sa.String(length=32), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo_emenda_raw', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.Enum('individual_finalidade_definida', 'individual_transferencia_especial', 'bancada', 'comissao', 'relator', 'outro', name='amendmenttype'), nullable=False),
    sa.Column('siop_author_code', sa.String(length=16), nullable=True),
    sa.Column('author_name_raw', sa.String(length=255), nullable=True),
    sa.Column('author_name_normalizado', sa.String(length=255), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('mandate_id', sa.Uuid(), nullable=True),
    sa.Column('codigo_municipio_ibge', sa.String(length=16), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('codigo_uf_ibge', sa.String(length=16), nullable=True),
    sa.Column('uf', sa.String(length=64), nullable=True),
    sa.Column('regiao', sa.String(length=32), nullable=True),
    sa.Column('nome_funcao', sa.String(length=120), nullable=True),
    sa.Column('nome_subfuncao', sa.String(length=120), nullable=True),
    sa.Column('nome_programa', sa.String(length=255), nullable=True),
    sa.Column('nome_acao', sa.String(length=255), nullable=True),
    sa.Column('valor_empenhado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_liquidado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_resto_inscrito', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_resto_cancelado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_resto_pago', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandate.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index(op.f('ix_budget_amendment_ano'), 'budget_amendment', ['ano'], unique=False)
    op.create_index(op.f('ix_budget_amendment_author_name_normalizado'), 'budget_amendment', ['author_name_normalizado'], unique=False)
    op.create_index(op.f('ix_budget_amendment_codigo_emenda'), 'budget_amendment', ['codigo_emenda'], unique=False)
    op.create_index(op.f('ix_budget_amendment_mandate_id'), 'budget_amendment', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_budget_amendment_person_id'), 'budget_amendment', ['person_id'], unique=False)
    op.create_index(op.f('ix_budget_amendment_siop_author_code'), 'budget_amendment', ['siop_author_code'], unique=False)
    op.create_index(op.f('ix_budget_amendment_tipo'), 'budget_amendment', ['tipo'], unique=False)
    op.create_index(op.f('ix_budget_amendment_uf'), 'budget_amendment', ['uf'], unique=False)
    op.create_table('campaign_expense',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('sq_despesa', sa.String(length=32), nullable=True),
    sa.Column('sq_candidato', sa.String(length=32), nullable=True),
    sa.Column('sq_prestador_contas', sa.String(length=32), nullable=True),
    sa.Column('ano_eleicao', sa.Integer(), nullable=False),
    sa.Column('st_turno', sa.Integer(), nullable=True),
    sa.Column('tp_prestacao_contas', postgresql.ENUM('final', 'parcial', 'relatorio_financeiro', 'regularizacao_omissao', 'outro', name='accountfiling', create_type=False), nullable=False),
    sa.Column('dt_despesa', sa.Date(), nullable=True),
    sa.Column('vr_despesa_contratada', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ds_despesa', sa.Text(), nullable=True),
    sa.Column('ds_origem_despesa', sa.String(length=255), nullable=True),
    sa.Column('ds_tipo_documento', sa.String(length=120), nullable=True),
    sa.Column('nr_documento', sa.String(length=64), nullable=True),
    sa.Column('nr_cpf_cnpj_fornecedor', sa.String(length=20), nullable=True),
    sa.Column('nm_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('nm_fornecedor_rfb', sa.String(length=255), nullable=True),
    sa.Column('ds_cnae_fornecedor', sa.String(length=255), nullable=True),
    sa.Column('sg_uf_fornecedor', sa.String(length=2), nullable=True),
    sa.Column('nm_municipio_fornecedor', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index(op.f('ix_campaign_expense_ano_eleicao'), 'campaign_expense', ['ano_eleicao'], unique=False)
    op.create_index(op.f('ix_campaign_expense_nr_cpf_cnpj_fornecedor'), 'campaign_expense', ['nr_cpf_cnpj_fornecedor'], unique=False)
    op.create_index(op.f('ix_campaign_expense_sq_candidato'), 'campaign_expense', ['sq_candidato'], unique=False)
    op.create_index(op.f('ix_campaign_expense_sq_despesa'), 'campaign_expense', ['sq_despesa'], unique=False)
    op.create_index(op.f('ix_campaign_expense_sq_prestador_contas'), 'campaign_expense', ['sq_prestador_contas'], unique=False)
    op.create_index(op.f('ix_campaign_expense_tp_prestacao_contas'), 'campaign_expense', ['tp_prestacao_contas'], unique=False)
    op.create_table('campaign_payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('sq_despesa', sa.String(length=32), nullable=True),
    sa.Column('sq_parcelamento_despesa', sa.String(length=32), nullable=True),
    sa.Column('sq_prestador_contas', sa.String(length=32), nullable=True),
    sa.Column('sq_candidato', sa.String(length=32), nullable=True),
    sa.Column('ano_eleicao', sa.Integer(), nullable=False),
    sa.Column('st_turno', sa.Integer(), nullable=True),
    sa.Column('tp_prestacao_contas', postgresql.ENUM('final', 'parcial', 'relatorio_financeiro', 'regularizacao_omissao', 'outro', name='accountfiling', create_type=False), nullable=False),
    sa.Column('dt_pagto_despesa', sa.Date(), nullable=True),
    sa.Column('vr_pagto_despesa', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ds_despesa', sa.Text(), nullable=True),
    sa.Column('ds_natureza_despesa', sa.String(length=120), nullable=True),
    sa.Column('ds_especie_recurso', sa.String(length=120), nullable=True),
    sa.Column('ds_fonte_despesa', sa.String(length=120), nullable=True),
    sa.Column('ds_origem_despesa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index(op.f('ix_campaign_payment_ano_eleicao'), 'campaign_payment', ['ano_eleicao'], unique=False)
    op.create_index(op.f('ix_campaign_payment_sq_candidato'), 'campaign_payment', ['sq_candidato'], unique=False)
    op.create_index(op.f('ix_campaign_payment_sq_despesa'), 'campaign_payment', ['sq_despesa'], unique=False)
    op.create_index(op.f('ix_campaign_payment_sq_prestador_contas'), 'campaign_payment', ['sq_prestador_contas'], unique=False)
    op.create_index(op.f('ix_campaign_payment_tp_prestacao_contas'), 'campaign_payment', ['tp_prestacao_contas'], unique=False)
    op.create_table('campaign_revenue',
    sa.Column('sq_receita', sa.String(length=32), nullable=False),
    sa.Column('sq_candidato', sa.String(length=32), nullable=True),
    sa.Column('sq_prestador_contas', sa.String(length=32), nullable=True),
    sa.Column('ano_eleicao', sa.Integer(), nullable=False),
    sa.Column('st_turno', sa.Integer(), nullable=True),
    sa.Column('tp_prestacao_contas', postgresql.ENUM('final', 'parcial', 'relatorio_financeiro', 'regularizacao_omissao', 'outro', name='accountfiling', create_type=False), nullable=False),
    sa.Column('dt_prestacao_contas', sa.Date(), nullable=True),
    sa.Column('dt_receita', sa.Date(), nullable=True),
    sa.Column('vr_receita', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ds_receita', sa.Text(), nullable=True),
    sa.Column('ds_fonte_receita', sa.String(length=120), nullable=True),
    sa.Column('ds_origem_receita', sa.String(length=160), nullable=True),
    sa.Column('ds_natureza_receita', sa.String(length=160), nullable=True),
    sa.Column('ds_especie_receita', sa.String(length=120), nullable=True),
    sa.Column('nr_cpf_cnpj_doador', sa.String(length=20), nullable=True),
    sa.Column('nm_doador', sa.String(length=255), nullable=True),
    sa.Column('nm_doador_rfb', sa.String(length=255), nullable=True),
    sa.Column('ds_cnae_doador', sa.String(length=255), nullable=True),
    sa.Column('sg_uf_doador', sa.String(length=2), nullable=True),
    sa.Column('nm_municipio_doador', sa.String(length=120), nullable=True),
    sa.Column('sq_candidato_doador', sa.String(length=32), nullable=True),
    sa.Column('sg_partido_doador', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['sq_candidato'], ['candidacy.sq_candidato'], ),
    sa.PrimaryKeyConstraint('sq_receita')
    )
    op.create_index(op.f('ix_campaign_revenue_ano_eleicao'), 'campaign_revenue', ['ano_eleicao'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_nr_cpf_cnpj_doador'), 'campaign_revenue', ['nr_cpf_cnpj_doador'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_sq_candidato'), 'campaign_revenue', ['sq_candidato'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_sq_candidato_doador'), 'campaign_revenue', ['sq_candidato_doador'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_sq_prestador_contas'), 'campaign_revenue', ['sq_prestador_contas'], unique=False)
    op.create_index(op.f('ix_campaign_revenue_tp_prestacao_contas'), 'campaign_revenue', ['tp_prestacao_contas'], unique=False)
    op.create_table('campaign_revenue_originator',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sq_receita', sa.String(length=32), nullable=False),
    sa.Column('nr_cpf_cnpj_doador_originario', sa.String(length=20), nullable=False),
    sa.Column('nm_doador_originario', sa.String(length=255), nullable=True),
    sa.Column('nm_doador_originario_rfb', sa.String(length=255), nullable=True),
    sa.Column('tp_doador_originario', sa.String(length=64), nullable=True),
    sa.Column('ds_cnae_doador_originario', sa.String(length=255), nullable=True),
    sa.Column('vr_receita', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['sq_receita'], ['campaign_revenue.sq_receita'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sq_receita', 'nr_cpf_cnpj_doador_originario')
    )
    op.create_index(op.f('ix_campaign_revenue_originator_sq_receita'), 'campaign_revenue_originator', ['sq_receita'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_revenue_originator_sq_receita'), table_name='campaign_revenue_originator')
    op.drop_table('campaign_revenue_originator')
    op.drop_index(op.f('ix_campaign_revenue_tp_prestacao_contas'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_sq_prestador_contas'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_sq_candidato_doador'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_sq_candidato'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_nr_cpf_cnpj_doador'), table_name='campaign_revenue')
    op.drop_index(op.f('ix_campaign_revenue_ano_eleicao'), table_name='campaign_revenue')
    op.drop_table('campaign_revenue')
    op.drop_index(op.f('ix_campaign_payment_tp_prestacao_contas'), table_name='campaign_payment')
    op.drop_index(op.f('ix_campaign_payment_sq_prestador_contas'), table_name='campaign_payment')
    op.drop_index(op.f('ix_campaign_payment_sq_despesa'), table_name='campaign_payment')
    op.drop_index(op.f('ix_campaign_payment_sq_candidato'), table_name='campaign_payment')
    op.drop_index(op.f('ix_campaign_payment_ano_eleicao'), table_name='campaign_payment')
    op.drop_table('campaign_payment')
    op.drop_index(op.f('ix_campaign_expense_tp_prestacao_contas'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_sq_prestador_contas'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_sq_despesa'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_sq_candidato'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_nr_cpf_cnpj_fornecedor'), table_name='campaign_expense')
    op.drop_index(op.f('ix_campaign_expense_ano_eleicao'), table_name='campaign_expense')
    op.drop_table('campaign_expense')
    op.drop_index(op.f('ix_budget_amendment_uf'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_tipo'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_siop_author_code'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_person_id'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_mandate_id'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_codigo_emenda'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_author_name_normalizado'), table_name='budget_amendment')
    op.drop_index(op.f('ix_budget_amendment_ano'), table_name='budget_amendment')
    op.drop_table('budget_amendment')
    op.drop_index(op.f('ix_amendment_author_link_siop_author_code'), table_name='amendment_author_link')
    op.drop_index(op.f('ix_amendment_author_link_person_id'), table_name='amendment_author_link')
    op.drop_index(op.f('ix_amendment_author_link_mandate_id'), table_name='amendment_author_link')
    op.drop_index(op.f('ix_amendment_author_link_ano'), table_name='amendment_author_link')
    op.drop_table('amendment_author_link')
    # ### end Alembic commands ###
    postgresql.ENUM(name='accountfiling').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='amendmenttype').drop(op.get_bind(), checkfirst=True)
