"""expense row_hash identity

Revision ID: d9f2937618b0
Revises: 4d2b3e1703af
Create Date: 2026-06-17 18:43:37.469843
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd9f2937618b0'
down_revision: str | None = '4d2b3e1703af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidacy_nome_norm_trgm'), table_name='candidacy', postgresql_ops={'nome_normalizado': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('expense', sa.Column('row_hash', sa.String(length=64), nullable=False))
    op.add_column('expense', sa.Column('parcela', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('expense_house_member_id_ano_mes_cod_documento_num_documento_key'), 'expense', type_='unique')
    op.create_unique_constraint(None, 'expense', ['row_hash'])
    op.drop_index(op.f('ix_person_nome_norm_trgm'), table_name='person', postgresql_ops={'nome_normalizado': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_person_nome_norm_trgm'), 'person', ['nome_normalizado'], unique=False, postgresql_ops={'nome_normalizado': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(None, 'expense', type_='unique')
    op.create_unique_constraint(op.f('expense_house_member_id_ano_mes_cod_documento_num_documento_key'), 'expense', ['house_member_id', 'ano', 'mes', 'cod_documento', 'num_documento'], postgresql_nulls_not_distinct=False)
    op.drop_column('expense', 'parcela')
    op.drop_column('expense', 'row_hash')
    op.create_index(op.f('ix_candidacy_nome_norm_trgm'), 'candidacy', ['nome_normalizado'], unique=False, postgresql_ops={'nome_normalizado': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
